version: '2'
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_PASSWORD: "123456"
            MYSQL_USER: "root"
            MYSQL_DATABASE: "order_challenge"
        volumes:
            - ./data:/docker-entrypoint-initdb.d
        networks:
            - main_network

    php:
        build: ./image/php/
        ports:
            - 9000:9000
        volumes:
            - ./src:/var/www/html
        networks:
            - main_network

    nginx:
        build: ./image/nginx
        ports:
            - 8080:80
        networks:
            - main_network

networks:
    main_network:
        driver: bridge
