version: '2'
services:
    mysql:
        container_name: orderapi_mysql
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./data:/docker-entrypoint-initdb.d
        networks:
            - main_network

    php:
        container_name: orderapi_php
        build:
            context: .
            dockerfile: ./image/php/Dockerfile
        ports:
            - 9000:9000
        volumes:
            - ./src:/var/www/html
        networks:
            - main_network

    nginx:
        container_name: orderapi_nginx
        build: ./image/nginx
        ports:
            - 8080:80
        networks:
            - main_network

networks:
    main_network:
        driver: bridge
